name: CI GitHub Actions pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Validate POM file
      run: mvn validate

    - name: Compile the code
      run: mvn compile

    - name: Run tests
      run: mvn test

    - name: Package the application
      run: mvn package

    - name: Deploy WAR file
      run: cp target/hello-world-web.war ${{ github.workspace }}/deployment/
      env:
        WAR_FILE: target/hello-world-web.war
