name: CI 2 for Hello World Web

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Validate POM file
      run: mvn validate

    - name: Compile the code
      run: mvn compile

    - name: Run tests
      run: mvn test

    - name: Package the application
      run: mvn package
    - name: Create deployment directory
      run: mkdir -p /home/runner/work/hello-world-web/hello-world-web/deployment

    - name: Deploy WAR file
      run: cp target/hello-world-web.war ${{ github.workspace }}/deployment/
      env:
        WAR_FILE: target/hello-world-web.war

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy WAR to Tomcat Server
      run: |
         scp -P 9090 target/hello-world-web.war sspl@192.168.1.107:**/usr/local/tomcat/webapps/
      env:
        WAR_FILE: target/hello-world-web.war
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
        TOMCAT_PORT: ${{ secrets.TOMCAT_PORT }}
